export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCES = 'ADD_PRODUCT_SUCCES';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const BEGIN_DOWNLOAD_PRODUCTS = 'BEGIN_DOWNLOAD_PRODUCTS';
export const DOWNLOAD_PRODUCTS_SUCCESS = 'DOWNLOAD_PRODUCTS_SUCCESS';
export const DOWNLOAD_PRODUCTS_ERROR = 'DOWNLOAD_PRODUCTS_ERROR';

export const GET_PRODUCT_DELETE = 'GET_PRODUCT_DELETE';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_ERROR = 'PRODUCT_DELETE_ERROR';

export const GET_PRODUCT_EDIT = 'GET_PRODUCT_EDIT';
export const BEGIN_EDIT_PRODUCT = 'BEGIN_EDIT_PRODUCT';
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS';
export const PRODUCT_EDIT_ERROR = 'PRODUCT_EDIT_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDDEN_ALERT = 'HIDDEN_ALERT'
